Add Traffic-Optimization product schema
travelgateX/graphql-schema pull request #292
Opened 2021-12-15 09:07 UTC by syordanov94

2021-12-17 09:45 UTC, arquio commented on trafficoptimization/to/inputs/input_TrafficOptimizationConnectionCollectionWhereInput.graphql
> +  # Buyer's organization code
code: ID! #top2kasdgf34nt

2021-12-17 10:07 UTC, arquio commented on admin/core/commons/common_TrafficOptimizationQuery.graphql
> +  trafficOptimizationConnectionCollection(data: TrafficOptimizationConnectionCollectionWhereInput): TrafficOptimizationConnectionCollection!
Listados: allObjeto: [Objeto]
Caso único: objeto:Objeto
isActive (idObjeto):Boolean
allObjectbyOrgGroupbyORGtype()

2021-12-17 10:07 UTC, arquio reviewed
Comentarios añadidos de la reu teniada. Pte sentarnos el lunes

2021-12-21 11:20 UTC, slucea requested changes
Cambiar naming para booleanos por isName

2021-12-21 11:20 UTC, slucea commented on trafficoptimization/to/inputs/input_TrafficOptimizationConnectionCollectionWhereInput.graphql
> +  active: Boolean
Cambiar naming a isActive

2021-12-21 12:00 UTC, slucea commented on trafficoptimization/to/inputs/input_TrafficOptimizationConnectionCollectionWhereInput.graphql
> +  accessCode:[ID!]
accessCode_in

2022-01-12 07:40 UTC, closed without merging