Add Transport / Ferry Schema
travelgateX/graphql-schema pull request #389
Opened 2023-03-14 11:34 UTC by hectorescalante

2023-03-14 13:56 UTC, bloodyrafo75 commented
Please fix on:
5846:6 There can be only one type named "Destination".   invalid-graphql-schema
8162:6 There can be only one type named "CancelPolicy".  invalid-graphql-schema
8838:6 There can be only one type named "Price".         invalid-graphql-schema
8841:3 Field "Price.currency" can only be defined once.  invalid-graphql-schema
8851:3 Field "[Price.net](http://price.net/)" can only be defined once.       invalid-graphql-schema
8854:3 Field "Price.gross" can only be defined once.     invalid-graphql-schema

2023-03-16 11:40 UTC, bloodyrafo75 requested changes

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/enums/enum_AdviseMessageLevel.graphql
please remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/enums/enum_CancelPenaltyType.graphql
Please remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/inputs/input_HolderInput.graphql
Please fix or remove  this file, it's previously defined in general schema with an extra field.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_AdviseMessage.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_Attributes.graphql
Please, rename this to vehicle attributes or similar.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_CancelPenalty.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_CancelPolicy.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_Contact.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_Exchange.graphql
Please  remove this file, it's previously defined in general schema. (check on the types u require)

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_ExternalMessage.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_Holder.graphql
Please  remove this file, it's previously defined in general schema. You have to add contact to the existing Holder type (as no mandatory to avoid conflicts)

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_Markup.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_PageInfo.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_Price.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/objects/object_Rule.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 11:40 UTC, bloodyrafo75 commented on transport/ferry/scalars/scalar_DateTime.graphql
Please  remove this file, it's previously defined in general schema.

2023-03-16 12:40 UTC, hectorescalante commented
Resueltos los conflictos:

2023-03-16 12:40 UTC, hectorescalante commented
PS C:\Users\hescalante\source\repos\graphql-schema> npm run validate

> test@1.0.0 validate
> graphql-schema-linter

[
  'C:\\Users\\hescalante\\source\\repos\\graphql-schema/full_schema.graphql'
]
C:\Users\hescalante\source\repos\graphql-schema\full_schema.graphql

2023-03-16 15:30 UTC, merged